AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Runtime: nodejs20.x

Resources:
  CreateTodoFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler
      CodeUri: src/createTodo/
      Events:
        CreateTodo:
          Type: Api
          Properties:
            Path: /todos
            Method: post

  GetTodoFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler
      CodeUri: src/getTodo/
      Events:
        GetTodo:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: get

  UpdateTodoFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler
      CodeUri: src/updateTodo/
      Events:
        UpdateTodo:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: put

  DeleteTodoFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler
      CodeUri: src/deleteTodo/
      Events:
        DeleteTodo:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: delete

  TodosTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Todos'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
